name: helix_workspace
publish_to: none

environment:
  sdk: ^3.12.0

workspace:
  - apps/helix_local
  - apps/helix_remote
  - tool
  - packages/local/helix_local_domain
  - packages/local/helix_local_protocol
  - packages/local/helix_local_crypto
  - packages/local/helix_local_transport
  - packages/local/helix_local_storage
  - packages/local/helix_local_platform
  - packages/local/helix_local_calls
  - packages/local/helix_local_messaging
  - packages/local/helix_local_transfer
  - packages/local/helix_local_groups
  - packages/local/helix_local_discovery
  - packages/remote/helix_remote_domain
  - packages/remote/helix_remote_api
  - packages/remote/helix_remote_crypto
  - services/helix_remote_backend



dependencies:
  helix_local_domain:
    path: packages/local/helix_local_domain
  helix_local_protocol:
    path: packages/local/helix_local_protocol
