// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'dart:typed_data' as i2;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    messagesFts,
    conversations,
    messages,
    messageReactions,
    messageReceipts,
    attachments,
    messagesUnread,
    messagesMessageId,
    messagesExpiresAt,
    conversationMembers,
    conversationsList,
    conversationMembersAccount,
    selfAccount,
    selfDevices,
    people,
    personDevices,
    identity,
    sessions,
    prekeys,
    senderKeys,
    inboxCursor,
    processedEnvelopes,
    outboxOps,
    deferredActions,
    transferJobs,
    transferChunks,
    groups,
    groupMembers,
    groupBans,
    callLog,
    settings,
    peoplePhoneHash,
    processedEnvelopesAt,
    outboxOpsDue,
    deferredActionsTarget,
    deferredActionsExpiry,
    transferJobsState,
    transferChunksTransfer,
    groupsList,
    groupMembersAccount,
    callLogAt,
  ];
  late final Shape0 messagesFts = Shape0(
    source: i0.VersionedVirtualTable(
      entityName: 'messages_fts',
      moduleAndArgs:
          'fts5(body, content = \'messages\', content_rowid = \'local_rowid\', tokenize = \'unicode61 remove_diacritics 2 categories \'\'L* N* Co M*\'\'\')',
      columns: [_column_0],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 conversations = Shape1(
    source: i0.VersionedTable(
      entityName: 'conversations',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 messages = Shape2(
    source: i0.VersionedTable(
      entityName: 'messages',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'UNIQUE(message_id, sender)',
        'UNIQUE(conversation_id, sort_key)',
      ],
      columns: [
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_2,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 messageReactions = Shape3(
    source: i0.VersionedTable(
      entityName: 'message_reactions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(message_rowid, reactor)'],
      columns: [_column_39, _column_40, _column_41, _column_42],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 messageReceipts = Shape4(
    source: i0.VersionedTable(
      entityName: 'message_receipts',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(message_rowid, account_id)'],
      columns: [_column_39, _column_43, _column_44, _column_45, _column_46],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 attachments = Shape5(
    source: i0.VersionedTable(
      entityName: 'attachments',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(message_rowid, position)'],
      columns: [
        _column_47,
        _column_39,
        _column_48,
        _column_2,
        _column_49,
        _column_50,
        _column_51,
        _column_52,
        _column_53,
        _column_54,
        _column_55,
        _column_56,
        _column_57,
        _column_58,
        _column_59,
        _column_60,
        _column_61,
        _column_62,
        _column_63,
        _column_64,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index messagesUnread = i1.Index(
    'messages_unread',
    'CREATE INDEX messages_unread ON messages (conversation_id, status)',
  );
  final i1.Index messagesMessageId = i1.Index(
    'messages_message_id',
    'CREATE INDEX messages_message_id ON messages (message_id)',
  );
  final i1.Index messagesExpiresAt = i1.Index(
    'messages_expires_at',
    'CREATE INDEX messages_expires_at ON messages (expires_at)',
  );
  late final Shape6 conversationMembers = Shape6(
    source: i0.VersionedTable(
      entityName: 'conversation_members',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(conversation_id, account_id)'],
      columns: [_column_20, _column_43, _column_65],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index conversationsList = i1.Index(
    'conversations_list',
    'CREATE INDEX conversations_list ON conversations (archived, last_message_at)',
  );
  final i1.Index conversationMembersAccount = i1.Index(
    'conversation_members_account',
    'CREATE INDEX conversation_members_account ON conversation_members (account_id)',
  );
  late final Shape7 selfAccount = Shape7(
    source: i0.VersionedTable(
      entityName: 'self_account',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)', 'CHECK(id = 1)'],
      columns: [
        _column_66,
        _column_43,
        _column_67,
        _column_68,
        _column_69,
        _column_70,
        _column_71,
        _column_72,
        _column_73,
        _column_74,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 selfDevices = Shape8(
    source: i0.VersionedTable(
      entityName: 'self_devices',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(device_id)'],
      columns: [
        _column_67,
        _column_54,
        _column_75,
        _column_76,
        _column_77,
        _column_78,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 people = Shape9(
    source: i0.VersionedTable(
      entityName: 'people',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(account_id)'],
      columns: [
        _column_43,
        _column_69,
        _column_70,
        _column_79,
        _column_80,
        _column_81,
        _column_71,
        _column_72,
        _column_82,
        _column_83,
        _column_84,
        _column_85,
        _column_86,
        _column_87,
        _column_88,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 personDevices = Shape10(
    source: i0.VersionedTable(
      entityName: 'person_devices',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(account_id, device_id)'],
      columns: [
        _column_43,
        _column_67,
        _column_89,
        _column_90,
        _column_91,
        _column_92,
        _column_93,
        _column_88,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 identity = Shape11(
    source: i0.VersionedTable(
      entityName: 'identity',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)', 'CHECK(id = 1)'],
      columns: [
        _column_66,
        _column_43,
        _column_67,
        _column_94,
        _column_95,
        _column_96,
        _column_97,
        _column_98,
        _column_99,
        _column_100,
        _column_17,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 sessions = Shape12(
    source: i0.VersionedTable(
      entityName: 'sessions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(peer_account_id, peer_device_id, slot)',
        'CHECK(slot BETWEEN 0 AND 5)',
      ],
      columns: [
        _column_101,
        _column_102,
        _column_103,
        _column_104,
        _column_17,
        _column_88,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape13 prekeys = Shape13(
    source: i0.VersionedTable(
      entityName: 'prekeys',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(kind, key_id)'],
      columns: [
        _column_2,
        _column_105,
        _column_106,
        _column_107,
        _column_108,
        _column_17,
        _column_109,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape14 senderKeys = Shape14(
    source: i0.VersionedTable(
      entityName: 'sender_keys',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(group_id, account_id, device_id, dist_id)',
      ],
      columns: [
        _column_110,
        _column_43,
        _column_67,
        _column_111,
        _column_104,
        _column_17,
        _column_88,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape15 inboxCursor = Shape15(
    source: i0.VersionedTable(
      entityName: 'inbox_cursor',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)', 'CHECK(id = 1)'],
      columns: [_column_66, _column_112, _column_113, _column_88],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape16 processedEnvelopes = Shape16(
    source: i0.VersionedTable(
      entityName: 'processed_envelopes',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(envelope_id, sender_device)'],
      columns: [
        _column_114,
        _column_115,
        _column_116,
        _column_117,
        _column_118,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape17 outboxOps = Shape17(
    source: i0.VersionedTable(
      entityName: 'outbox_ops',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_47,
        _column_2,
        _column_119,
        _column_120,
        _column_121,
        _column_122,
        _column_123,
        _column_124,
        _column_125,
        _column_126,
        _column_127,
        _column_17,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape18 deferredActions = Shape18(
    source: i0.VersionedTable(
      entityName: 'deferred_actions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_47,
        _column_128,
        _column_129,
        _column_21,
        _column_22,
        _column_2,
        _column_122,
        _column_26,
        _column_130,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape19 transferJobs = Shape19(
    source: i0.VersionedTable(
      entityName: 'transfer_jobs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(attachment_rowid)'],
      columns: [
        _column_47,
        _column_2,
        _column_131,
        _column_132,
        _column_63,
        _column_133,
        _column_134,
        _column_135,
        _column_136,
        _column_123,
        _column_124,
        _column_125,
        _column_126,
        _column_127,
        _column_17,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape20 transferChunks = Shape20(
    source: i0.VersionedTable(
      entityName: 'transfer_chunks',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(transfer_id, sequence)'],
      columns: [
        _column_137,
        _column_138,
        _column_139,
        _column_140,
        _column_141,
        _column_26,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape21 groups = Shape21(
    source: i0.VersionedTable(
      entityName: 'groups',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_1,
        _column_142,
        _column_4,
        _column_143,
        _column_144,
        _column_145,
        _column_146,
        _column_7,
        _column_147,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_17,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape22 groupMembers = Shape22(
    source: i0.VersionedTable(
      entityName: 'group_members',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(group_id, account_id)'],
      columns: [
        _column_148,
        _column_43,
        _column_149,
        _column_150,
        _column_143,
        _column_151,
        _column_152,
        _column_153,
        _column_65,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape23 groupBans = Shape23(
    source: i0.VersionedTable(
      entityName: 'group_bans',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(group_id, account_id)'],
      columns: [_column_148, _column_43, _column_154],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape24 callLog = Shape24(
    source: i0.VersionedTable(
      entityName: 'call_log',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(call_id)'],
      columns: [
        _column_155,
        _column_101,
        _column_156,
        _column_2,
        _column_157,
        _column_158,
        _column_123,
        _column_159,
        _column_160,
        _column_161,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape25 settings = Shape25(
    source: i0.VersionedTable(
      entityName: 'settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_162, _column_163, _column_88],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index peoplePhoneHash = i1.Index(
    'people_phone_hash',
    'CREATE INDEX people_phone_hash ON people (phone_hash)',
  );
  final i1.Index processedEnvelopesAt = i1.Index(
    'processed_envelopes_at',
    'CREATE INDEX processed_envelopes_at ON processed_envelopes (processed_at)',
  );
  final i1.Index outboxOpsDue = i1.Index(
    'outbox_ops_due',
    'CREATE INDEX outbox_ops_due ON outbox_ops (state, next_attempt_at)',
  );
  final i1.Index deferredActionsTarget = i1.Index(
    'deferred_actions_target',
    'CREATE INDEX deferred_actions_target ON deferred_actions (target_message_id, target_author)',
  );
  final i1.Index deferredActionsExpiry = i1.Index(
    'deferred_actions_expiry',
    'CREATE INDEX deferred_actions_expiry ON deferred_actions (expires_at)',
  );
  final i1.Index transferJobsState = i1.Index(
    'transfer_jobs_state',
    'CREATE INDEX transfer_jobs_state ON transfer_jobs (state, next_attempt_at)',
  );
  final i1.Index transferChunksTransfer = i1.Index(
    'transfer_chunks_transfer',
    'CREATE INDEX transfer_chunks_transfer ON transfer_chunks (transfer_id, sequence)',
  );
  final i1.Index groupsList = i1.Index(
    'groups_list',
    'CREATE INDEX groups_list ON "groups" (archived)',
  );
  final i1.Index groupMembersAccount = i1.Index(
    'group_members_account',
    'CREATE INDEX group_members_account ON group_members (account_id)',
  );
  final i1.Index callLogAt = i1.Index(
    'call_log_at',
    'CREATE INDEX call_log_at ON call_log (started_at)',
  );
}

class Shape0 extends i0.VersionedVirtualTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get body =>
      columnsByName['body']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_0(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'body',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get kind =>
      columnsByName['kind']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<i2.Uint8List> get avatar =>
      columnsByName['avatar']! as i1.GeneratedColumn<i2.Uint8List>;
  i1.GeneratedColumn<int> get pinnedAt =>
      columnsByName['pinned_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get mutedUntil =>
      columnsByName['muted_until']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get archived =>
      columnsByName['archived']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lastMessageRowid =>
      columnsByName['last_message_rowid']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get lastMessageSortKey =>
      columnsByName['last_message_sort_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get lastMessageAt =>
      columnsByName['last_message_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get lastMessagePreview =>
      columnsByName['last_message_preview']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get unreadCount =>
      columnsByName['unread_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get mentionCount =>
      columnsByName['mention_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get lastReadSortKey =>
      columnsByName['last_read_sort_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get draft =>
      columnsByName['draft']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get disappearingSeconds =>
      columnsByName['disappearing_seconds']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'kind',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_3(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'title',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<i2.Uint8List> _column_4(String aliasedName) =>
    i1.GeneratedColumn<i2.Uint8List>(
      'avatar',
      aliasedName,
      true,
      type: i1.DriftSqlType.blob,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_5(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'pinned_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_6(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'muted_until',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_7(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'archived',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (archived IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_8(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'last_message_rowid',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_9(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'last_message_sort_key',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_10(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'last_message_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_11(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'last_message_preview',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_12(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'unread_count',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_13(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'mention_count',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_14(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'last_read_sort_key',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_15(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'draft',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_16(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'disappearing_seconds',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_17(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'created_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get localRowid =>
      columnsByName['local_rowid']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get messageId =>
      columnsByName['message_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get conversationId =>
      columnsByName['conversation_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sender =>
      columnsByName['sender']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get senderDevice =>
      columnsByName['sender_device']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get outgoing =>
      columnsByName['outgoing']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get sortKey =>
      columnsByName['sort_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get sentAt =>
      columnsByName['sent_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get receivedAt =>
      columnsByName['received_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get kind =>
      columnsByName['kind']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get body =>
      columnsByName['body']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get payload =>
      columnsByName['payload']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get replyToId =>
      columnsByName['reply_to_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get replyToAuthor =>
      columnsByName['reply_to_author']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get forwarded =>
      columnsByName['forwarded']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get mentionsMe =>
      columnsByName['mentions_me']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get editedAt =>
      columnsByName['edited_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get expireSeconds =>
      columnsByName['expire_seconds']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get expiresAt =>
      columnsByName['expires_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get viewOnceState =>
      columnsByName['view_once_state']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_18(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'local_rowid',
      aliasedName,
      false,
      hasAutoIncrement: true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL PRIMARY KEY AUTOINCREMENT',
    );
i1.GeneratedColumn<String> _column_19(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'message_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_20(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'conversation_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL REFERENCES conversations(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<String> _column_21(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'sender',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_22(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'sender_device',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_23(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'outgoing',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (outgoing IN (0, 1))',
    );
i1.GeneratedColumn<String> _column_24(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'sort_key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_25(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'sent_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_26(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'received_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_27(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'body',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_28(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'payload',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_29(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'reply_to_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_30(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'reply_to_author',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_31(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'forwarded',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (forwarded IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_32(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'mentions_me',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (mentions_me IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_33(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'status',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_34(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'edited_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_35(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'deleted_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_36(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'expire_seconds',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_37(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'expires_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_38(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'view_once_state',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get messageRowid =>
      columnsByName['message_rowid']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get reactor =>
      columnsByName['reactor']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get emoji =>
      columnsByName['emoji']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get reactedAt =>
      columnsByName['reacted_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_39(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'message_rowid',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL REFERENCES messages(local_rowid)ON DELETE CASCADE',
    );
i1.GeneratedColumn<String> _column_40(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'reactor',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_41(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'emoji',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_42(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'reacted_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get messageRowid =>
      columnsByName['message_rowid']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get accountId =>
      columnsByName['account_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get deliveredAt =>
      columnsByName['delivered_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get readAt =>
      columnsByName['read_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get viewedAt =>
      columnsByName['viewed_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_43(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'account_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_44(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'delivered_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_45(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'read_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_46(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'viewed_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get messageRowid =>
      columnsByName['message_rowid']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get position =>
      columnsByName['position']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get kind =>
      columnsByName['kind']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get mediaId =>
      columnsByName['media_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<i2.Uint8List> get mediaKey =>
      columnsByName['media_key']! as i1.GeneratedColumn<i2.Uint8List>;
  i1.GeneratedColumn<i2.Uint8List> get digest =>
      columnsByName['digest']! as i1.GeneratedColumn<i2.Uint8List>;
  i1.GeneratedColumn<String> get mime =>
      columnsByName['mime']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get size =>
      columnsByName['size']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get width =>
      columnsByName['width']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get height =>
      columnsByName['height']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get durationMs =>
      columnsByName['duration_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<i2.Uint8List> get waveform =>
      columnsByName['waveform']! as i1.GeneratedColumn<i2.Uint8List>;
  i1.GeneratedColumn<String> get blurhash =>
      columnsByName['blurhash']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get caption =>
      columnsByName['caption']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get thumbnail =>
      columnsByName['thumbnail']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get thumbnailPath =>
      columnsByName['thumbnail_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get localPath =>
      columnsByName['local_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get transfer =>
      columnsByName['transfer']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_47(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      hasAutoIncrement: true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL PRIMARY KEY AUTOINCREMENT',
    );
i1.GeneratedColumn<int> _column_48(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'position',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_49(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'media_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<i2.Uint8List> _column_50(String aliasedName) =>
    i1.GeneratedColumn<i2.Uint8List>(
      'media_key',
      aliasedName,
      false,
      type: i1.DriftSqlType.blob,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<i2.Uint8List> _column_51(String aliasedName) =>
    i1.GeneratedColumn<i2.Uint8List>(
      'digest',
      aliasedName,
      false,
      type: i1.DriftSqlType.blob,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_52(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'mime',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_53(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'size',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_54(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_55(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'width',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_56(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'height',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_57(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'duration_ms',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<i2.Uint8List> _column_58(String aliasedName) =>
    i1.GeneratedColumn<i2.Uint8List>(
      'waveform',
      aliasedName,
      true,
      type: i1.DriftSqlType.blob,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_59(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'blurhash',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_60(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'caption',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_61(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'thumbnail',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_62(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'thumbnail_path',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_63(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'local_path',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_64(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'transfer',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get conversationId =>
      columnsByName['conversation_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get accountId =>
      columnsByName['account_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get joinedAt =>
      columnsByName['joined_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_65(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'joined_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get accountId =>
      columnsByName['account_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get deviceId =>
      columnsByName['device_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get serverDomain =>
      columnsByName['server_domain']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get helixName =>
      columnsByName['helix_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get phoneNumber =>
      columnsByName['phone_number']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get profileName =>
      columnsByName['profile_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<i2.Uint8List> get profileKey =>
      columnsByName['profile_key']! as i1.GeneratedColumn<i2.Uint8List>;
  i1.GeneratedColumn<int> get profileVersion =>
      columnsByName['profile_version']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get registeredAt =>
      columnsByName['registered_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_66(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_67(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'device_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_68(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'server_domain',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_69(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'helix_name',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_70(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'phone_number',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_71(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'profile_name',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<i2.Uint8List> _column_72(String aliasedName) =>
    i1.GeneratedColumn<i2.Uint8List>(
      'profile_key',
      aliasedName,
      true,
      type: i1.DriftSqlType.blob,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_73(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'profile_version',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_74(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'registered_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get deviceId =>
      columnsByName['device_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get platform =>
      columnsByName['platform']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get linkedAt =>
      columnsByName['linked_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lastActiveAt =>
      columnsByName['last_active_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get isThisDevice =>
      columnsByName['is_this_device']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_75(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'platform',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_76(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'linked_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_77(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'last_active_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_78(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_this_device',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (is_this_device IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );

class Shape9 extends i0.VersionedTable {
  Shape9({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get accountId =>
      columnsByName['account_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get helixName =>
      columnsByName['helix_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get phoneNumber =>
      columnsByName['phone_number']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get phoneHash =>
      columnsByName['phone_hash']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get phonebookName =>
      columnsByName['phonebook_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get nickname =>
      columnsByName['nickname']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get profileName =>
      columnsByName['profile_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<i2.Uint8List> get profileKey =>
      columnsByName['profile_key']! as i1.GeneratedColumn<i2.Uint8List>;
  i1.GeneratedColumn<int> get profileVersion =>
      columnsByName['profile_version']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<i2.Uint8List> get avatarBlob =>
      columnsByName['avatar_blob']! as i1.GeneratedColumn<i2.Uint8List>;
  i1.GeneratedColumn<i2.Uint8List> get identityKey =>
      columnsByName['identity_key']! as i1.GeneratedColumn<i2.Uint8List>;
  i1.GeneratedColumn<int> get identityVerified =>
      columnsByName['identity_verified']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get identityChangedAt =>
      columnsByName['identity_changed_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get blocked =>
      columnsByName['blocked']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_79(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'phone_hash',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_80(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'phonebook_name',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_81(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'nickname',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_82(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'profile_version',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<i2.Uint8List> _column_83(String aliasedName) =>
    i1.GeneratedColumn<i2.Uint8List>(
      'avatar_blob',
      aliasedName,
      true,
      type: i1.DriftSqlType.blob,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<i2.Uint8List> _column_84(String aliasedName) =>
    i1.GeneratedColumn<i2.Uint8List>(
      'identity_key',
      aliasedName,
      true,
      type: i1.DriftSqlType.blob,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_85(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'identity_verified',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL DEFAULT 0 CHECK (identity_verified IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_86(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'identity_changed_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_87(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'blocked',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (blocked IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_88(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'updated_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape10 extends i0.VersionedTable {
  Shape10({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get accountId =>
      columnsByName['account_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get deviceId =>
      columnsByName['device_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<i2.Uint8List> get identityKey =>
      columnsByName['identity_key']! as i1.GeneratedColumn<i2.Uint8List>;
  i1.GeneratedColumn<i2.Uint8List> get signingKey =>
      columnsByName['signing_key']! as i1.GeneratedColumn<i2.Uint8List>;
  i1.GeneratedColumn<i2.Uint8List> get certificate =>
      columnsByName['certificate']! as i1.GeneratedColumn<i2.Uint8List>;
  i1.GeneratedColumn<String> get trust =>
      columnsByName['trust']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get firstSeenAt =>
      columnsByName['first_seen_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<i2.Uint8List> _column_89(String aliasedName) =>
    i1.GeneratedColumn<i2.Uint8List>(
      'identity_key',
      aliasedName,
      false,
      type: i1.DriftSqlType.blob,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<i2.Uint8List> _column_90(String aliasedName) =>
    i1.GeneratedColumn<i2.Uint8List>(
      'signing_key',
      aliasedName,
      false,
      type: i1.DriftSqlType.blob,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<i2.Uint8List> _column_91(String aliasedName) =>
    i1.GeneratedColumn<i2.Uint8List>(
      'certificate',
      aliasedName,
      true,
      type: i1.DriftSqlType.blob,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_92(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'trust',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_93(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'first_seen_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape11 extends i0.VersionedTable {
  Shape11({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get accountId =>
      columnsByName['account_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get deviceId =>
      columnsByName['device_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<i2.Uint8List> get aikPublic =>
      columnsByName['aik_public']! as i1.GeneratedColumn<i2.Uint8List>;
  i1.GeneratedColumn<i2.Uint8List> get aikPrivate =>
      columnsByName['aik_private']! as i1.GeneratedColumn<i2.Uint8List>;
  i1.GeneratedColumn<i2.Uint8List> get dikPublic =>
      columnsByName['dik_public']! as i1.GeneratedColumn<i2.Uint8List>;
  i1.GeneratedColumn<i2.Uint8List> get dikPrivate =>
      columnsByName['dik_private']! as i1.GeneratedColumn<i2.Uint8List>;
  i1.GeneratedColumn<i2.Uint8List> get dskPublic =>
      columnsByName['dsk_public']! as i1.GeneratedColumn<i2.Uint8List>;
  i1.GeneratedColumn<i2.Uint8List> get dskPrivate =>
      columnsByName['dsk_private']! as i1.GeneratedColumn<i2.Uint8List>;
  i1.GeneratedColumn<i2.Uint8List> get deviceCertificate =>
      columnsByName['device_certificate']! as i1.GeneratedColumn<i2.Uint8List>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<i2.Uint8List> _column_94(String aliasedName) =>
    i1.GeneratedColumn<i2.Uint8List>(
      'aik_public',
      aliasedName,
      false,
      type: i1.DriftSqlType.blob,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<i2.Uint8List> _column_95(String aliasedName) =>
    i1.GeneratedColumn<i2.Uint8List>(
      'aik_private',
      aliasedName,
      false,
      type: i1.DriftSqlType.blob,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<i2.Uint8List> _column_96(String aliasedName) =>
    i1.GeneratedColumn<i2.Uint8List>(
      'dik_public',
      aliasedName,
      false,
      type: i1.DriftSqlType.blob,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<i2.Uint8List> _column_97(String aliasedName) =>
    i1.GeneratedColumn<i2.Uint8List>(
      'dik_private',
      aliasedName,
      false,
      type: i1.DriftSqlType.blob,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<i2.Uint8List> _column_98(String aliasedName) =>
    i1.GeneratedColumn<i2.Uint8List>(
      'dsk_public',
      aliasedName,
      false,
      type: i1.DriftSqlType.blob,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<i2.Uint8List> _column_99(String aliasedName) =>
    i1.GeneratedColumn<i2.Uint8List>(
      'dsk_private',
      aliasedName,
      false,
      type: i1.DriftSqlType.blob,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<i2.Uint8List> _column_100(String aliasedName) =>
    i1.GeneratedColumn<i2.Uint8List>(
      'device_certificate',
      aliasedName,
      false,
      type: i1.DriftSqlType.blob,
      $customConstraints: 'NOT NULL',
    );

class Shape12 extends i0.VersionedTable {
  Shape12({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get peerAccountId =>
      columnsByName['peer_account_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get peerDeviceId =>
      columnsByName['peer_device_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get slot =>
      columnsByName['slot']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<i2.Uint8List> get state =>
      columnsByName['state']! as i1.GeneratedColumn<i2.Uint8List>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_101(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'peer_account_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_102(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'peer_device_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_103(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'slot',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<i2.Uint8List> _column_104(String aliasedName) =>
    i1.GeneratedColumn<i2.Uint8List>(
      'state',
      aliasedName,
      false,
      type: i1.DriftSqlType.blob,
      $customConstraints: 'NOT NULL',
    );

class Shape13 extends i0.VersionedTable {
  Shape13({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get kind =>
      columnsByName['kind']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get keyId =>
      columnsByName['key_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<i2.Uint8List> get publicKey =>
      columnsByName['public_key']! as i1.GeneratedColumn<i2.Uint8List>;
  i1.GeneratedColumn<i2.Uint8List> get privateKey =>
      columnsByName['private_key']! as i1.GeneratedColumn<i2.Uint8List>;
  i1.GeneratedColumn<i2.Uint8List> get signature =>
      columnsByName['signature']! as i1.GeneratedColumn<i2.Uint8List>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get retiredAt =>
      columnsByName['retired_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_105(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'key_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<i2.Uint8List> _column_106(String aliasedName) =>
    i1.GeneratedColumn<i2.Uint8List>(
      'public_key',
      aliasedName,
      false,
      type: i1.DriftSqlType.blob,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<i2.Uint8List> _column_107(String aliasedName) =>
    i1.GeneratedColumn<i2.Uint8List>(
      'private_key',
      aliasedName,
      false,
      type: i1.DriftSqlType.blob,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<i2.Uint8List> _column_108(String aliasedName) =>
    i1.GeneratedColumn<i2.Uint8List>(
      'signature',
      aliasedName,
      true,
      type: i1.DriftSqlType.blob,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_109(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'retired_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

class Shape14 extends i0.VersionedTable {
  Shape14({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get groupId =>
      columnsByName['group_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get accountId =>
      columnsByName['account_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get deviceId =>
      columnsByName['device_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get distId =>
      columnsByName['dist_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<i2.Uint8List> get state =>
      columnsByName['state']! as i1.GeneratedColumn<i2.Uint8List>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_110(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'group_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_111(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'dist_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape15 extends i0.VersionedTable {
  Shape15({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lastProcessedSeq =>
      columnsByName['last_processed_seq']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lastAckedSeq =>
      columnsByName['last_acked_seq']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_112(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'last_processed_seq',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_113(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'last_acked_seq',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );

class Shape16 extends i0.VersionedTable {
  Shape16({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get envelopeId =>
      columnsByName['envelope_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get senderDevice =>
      columnsByName['sender_device']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get seq =>
      columnsByName['seq']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get outcome =>
      columnsByName['outcome']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get processedAt =>
      columnsByName['processed_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_114(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'envelope_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_115(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'sender_device',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'\'',
      defaultValue: const i1.CustomExpression('\'\''),
    );
i1.GeneratedColumn<int> _column_116(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'seq',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_117(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'outcome',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_118(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'processed_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape17 extends i0.VersionedTable {
  Shape17({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get kind =>
      columnsByName['kind']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get conversationId =>
      columnsByName['conversation_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get messageRowid =>
      columnsByName['message_rowid']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get idempotencyKey =>
      columnsByName['idempotency_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get payload =>
      columnsByName['payload']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get state =>
      columnsByName['state']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get attempts =>
      columnsByName['attempts']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get nextAttemptAt =>
      columnsByName['next_attempt_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get leaseUntil =>
      columnsByName['lease_until']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get lastError =>
      columnsByName['last_error']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_119(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'conversation_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL REFERENCES conversations(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<int> _column_120(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'message_rowid',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NULL REFERENCES messages(local_rowid)ON DELETE CASCADE',
    );
i1.GeneratedColumn<String> _column_121(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'idempotency_key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL UNIQUE',
    );
i1.GeneratedColumn<String> _column_122(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'payload',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_123(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'state',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_124(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'attempts',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_125(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'next_attempt_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_126(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'lease_until',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_127(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'last_error',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape18 extends i0.VersionedTable {
  Shape18({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get targetMessageId =>
      columnsByName['target_message_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get targetAuthor =>
      columnsByName['target_author']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sender =>
      columnsByName['sender']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get senderDevice =>
      columnsByName['sender_device']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get kind =>
      columnsByName['kind']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get payload =>
      columnsByName['payload']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get receivedAt =>
      columnsByName['received_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get expiresAt =>
      columnsByName['expires_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_128(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'target_message_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_129(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'target_author',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_130(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'expires_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape19 extends i0.VersionedTable {
  Shape19({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get kind =>
      columnsByName['kind']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get attachmentRowid =>
      columnsByName['attachment_rowid']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get mediaId =>
      columnsByName['media_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get localPath =>
      columnsByName['local_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get size =>
      columnsByName['size']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get offset =>
      columnsByName['offset']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<i2.Uint8List> get mediaKey =>
      columnsByName['media_key']! as i1.GeneratedColumn<i2.Uint8List>;
  i1.GeneratedColumn<String> get purpose =>
      columnsByName['purpose']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get state =>
      columnsByName['state']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get attempts =>
      columnsByName['attempts']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get nextAttemptAt =>
      columnsByName['next_attempt_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get leaseUntil =>
      columnsByName['lease_until']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get lastError =>
      columnsByName['last_error']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_131(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'attachment_rowid',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL REFERENCES attachments(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<String> _column_132(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'media_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_133(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'size',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_134(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'offset',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<i2.Uint8List> _column_135(String aliasedName) =>
    i1.GeneratedColumn<i2.Uint8List>(
      'media_key',
      aliasedName,
      true,
      type: i1.DriftSqlType.blob,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_136(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'purpose',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape20 extends i0.VersionedTable {
  Shape20({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get transferId =>
      columnsByName['transfer_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get sequence =>
      columnsByName['sequence']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<i2.Uint8List> get payload =>
      columnsByName['payload']! as i1.GeneratedColumn<i2.Uint8List>;
  i1.GeneratedColumn<int> get total =>
      columnsByName['total']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get isFinal =>
      columnsByName['is_final']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get receivedAt =>
      columnsByName['received_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_137(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'transfer_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_138(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'sequence',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<i2.Uint8List> _column_139(String aliasedName) =>
    i1.GeneratedColumn<i2.Uint8List>(
      'payload',
      aliasedName,
      false,
      type: i1.DriftSqlType.blob,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_140(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'total',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_141(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_final',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (is_final IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );

class Shape21 extends i0.VersionedTable {
  Shape21({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<i2.Uint8List> get avatar =>
      columnsByName['avatar']! as i1.GeneratedColumn<i2.Uint8List>;
  i1.GeneratedColumn<String> get role =>
      columnsByName['role']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get epoch =>
      columnsByName['epoch']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<i2.Uint8List> get state =>
      columnsByName['state']! as i1.GeneratedColumn<i2.Uint8List>;
  i1.GeneratedColumn<int> get stateVersion =>
      columnsByName['state_version']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get archived =>
      columnsByName['archived']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get muted =>
      columnsByName['muted']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lastMessageRowid =>
      columnsByName['last_message_rowid']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get lastMessageSortKey =>
      columnsByName['last_message_sort_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get lastMessageAt =>
      columnsByName['last_message_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get lastMessagePreview =>
      columnsByName['last_message_preview']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get unreadCount =>
      columnsByName['unread_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get mentionCount =>
      columnsByName['mention_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_142(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'title',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_143(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'role',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_144(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'epoch',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<i2.Uint8List> _column_145(String aliasedName) =>
    i1.GeneratedColumn<i2.Uint8List>(
      'state',
      aliasedName,
      true,
      type: i1.DriftSqlType.blob,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_146(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'state_version',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_147(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'muted',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (muted IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );

class Shape22 extends i0.VersionedTable {
  Shape22({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get groupId =>
      columnsByName['group_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get accountId =>
      columnsByName['account_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get qualifiedId =>
      columnsByName['qualified_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get displayName =>
      columnsByName['display_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get role =>
      columnsByName['role']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get isSelf =>
      columnsByName['is_self']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get devicesJson =>
      columnsByName['devices_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get devicesFetchedAt =>
      columnsByName['devices_fetched_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get joinedAt =>
      columnsByName['joined_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_148(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'group_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES "groups"(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<String> _column_149(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'qualified_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_150(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'display_name',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_151(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_self',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (is_self IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_152(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'devices_json',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_153(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'devices_fetched_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

class Shape23 extends i0.VersionedTable {
  Shape23({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get groupId =>
      columnsByName['group_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get accountId =>
      columnsByName['account_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get bannedAt =>
      columnsByName['banned_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_154(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'banned_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape24 extends i0.VersionedTable {
  Shape24({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get callId =>
      columnsByName['call_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get peerAccountId =>
      columnsByName['peer_account_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get peerDisplayName =>
      columnsByName['peer_display_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get kind =>
      columnsByName['kind']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get direction =>
      columnsByName['direction']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get video =>
      columnsByName['video']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get state =>
      columnsByName['state']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get startedAt =>
      columnsByName['started_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get answeredAt =>
      columnsByName['answered_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get endedAt =>
      columnsByName['ended_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_155(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'call_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_156(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'peer_display_name',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_157(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'direction',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_158(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'video',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (video IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_159(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'started_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_160(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'answered_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_161(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'ended_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

class Shape25 extends i0.VersionedTable {
  Shape25({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get key =>
      columnsByName['key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get value =>
      columnsByName['value']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_162(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_163(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'value',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(from1To2: from1To2),
);
