name: helix_remote_cli
description: Pure Dart CLI client for Helix Remote.
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.12.0

resolution: workspace

dependencies:
  meta: ^1.18.0
  path: ^1.8.3
  sqlite3: ^3.3.3
  crypto: ^3.0.7
  cryptography: ^2.9.0
  helix_remote_api:
    path: ../helix_remote_api
  helix_remote_crypto:
    path: ../helix_remote_crypto
  helix_remote_db:
    path: ../helix_remote_db
  helix_remote_engine:
    path: ../helix_remote_engine
  helix_remote_protocol:
    path: ../helix_remote_protocol

dev_dependencies:
  helix_remote_architecture_rules:
    path: ../helix_remote_architecture_rules
  test: ^1.31.0
