name: helix_transfer
description: Clean File and Ephemeral Media Transfer Use Cases and Adapters for Helix
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.12.0

resolution: workspace

dependencies:
  crypto: any
  uuid: any
  image: any
  path: any
  helix_domain:
    path: ../helix_domain
  helix_protocol:
    path: ../helix_protocol
  helix_transport:
    path: ../helix_transport
