// Phase 4 — RP4-002 and RP4-004: message protector seed isolation.
//
// RemoteMessageProtectorImpl lives in the app package, so these tests cannot
// go into helix_remote_crypto. They verify:
//
//   RP4-002  X3DH or equivalent session setup is used — the protector uses a
//            per-session, non-static random seed (not a hard-coded global).
//   RP4-004  Local message history encryption does not rely on a static fallback
//            seed in release mode. Each conversation gets a distinct random seed
//            generated by dart:math.Random.secure().

import 'dart:ffi';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:helix_remote/app/remote_message_protector.dart';
import 'package:helix_remote_storage/helix_remote_storage.dart';
import 'package:path/path.dart' as pathpkg;

void _loadSqlCipher() {
  if (!Platform.isWindows) return;
  var dir = Directory.current;
  String? foundPath;
  for (var i = 0; i < 5; i++) {
    final candidate = pathpkg.join(
      dir.path,
      '.dart_tool',
      'lib',
      'sqlite3.dll',
    );
    if (File(candidate).existsSync()) {
      foundPath = candidate;
      break;
    }
    final parent = dir.parent;
    if (parent.path == dir.path) break;
    dir = parent;
  }
  if (foundPath != null) DynamicLibrary.open(foundPath);
}

void main() {
  setUpAll(_loadSqlCipher);

  // -------------------------------------------------------------------------
  // RP4-002 — Protector seed is per-session, not a static global
  // -------------------------------------------------------------------------

  group('RP4-002 — Message protector seed is per-session and non-static', () {
    test('generateSeed produces distinct values on every call', () {
      const n = 20;
      final seeds = {
        for (var i = 0; i < n; i++) RemoteMessageProtectorImpl.generateSeed(),
      };
      expect(
        seeds.length,
        equals(n),
        reason: 'All seeds must be unique — no static fallback',
      );
    });

    test('encrypt / decrypt round-trip with same seed', () async {
      const seed = 'test-seed-fixed-value-32bytes-xxx';
      final protector = RemoteMessageProtectorImpl(
        keySeedProvider: (_) => seed,
      );

      const plaintext = 'secret message content';
      final ct = await protector.encryptText(
        conversationId: 'conv-001',
        messageId: 'msg-1',
        plaintext: plaintext,
        recipientDeviceId: 'dev-001',
      );
      final decrypted = await protector.decryptText(
        conversationId: 'conv-001',
        messageId: 'msg-1',
        ciphertext: ct,
      );
      expect(decrypted, equals(plaintext));
    });

    test('wrong seed fails decryption with an exception', () async {
      final protector = RemoteMessageProtectorImpl(
        keySeedProvider: (_) => RemoteMessageProtectorImpl.generateSeed(),
      );
      final ct = await protector.encryptText(
        conversationId: 'conv-001',
        messageId: 'msg-1',
        plaintext: 'hello',
        recipientDeviceId: 'dev-001',
      );

      final wrongProtector = RemoteMessageProtectorImpl(
        keySeedProvider: (_) => RemoteMessageProtectorImpl.generateSeed(),
      );
      expect(
        () => wrongProtector.decryptText(
          conversationId: 'conv-001',
          messageId: 'msg-1',
          ciphertext: ct,
        ),
        throwsA(anything),
        reason: 'Wrong seed must fail AES-GCM authentication',
      );
    });

    test(
      'each encrypt call produces a distinct ciphertext (random nonce)',
      () async {
        const seed = 'nonce-test-seed-32bytes-xxxxxxxxx';
        final protector = RemoteMessageProtectorImpl(
          keySeedProvider: (_) => seed,
        );

        final ct1 = await protector.encryptText(
          conversationId: 'conv-001',
          messageId: 'msg-1',
          plaintext: 'hello',
          recipientDeviceId: 'dev-001',
        );
        final ct2 = await protector.encryptText(
          conversationId: 'conv-001',
          messageId: 'msg-2',
          plaintext: 'hello',
          recipientDeviceId: 'dev-001',
        );
        expect(
          ct1,
          isNot(equals(ct2)),
          reason: 'AES-GCM nonce must be random per call',
        );
      },
    );

    test(
      'different conversations get different keys (cross-conv decryption fails)',
      () async {
        const seeds = {
          'conv-a': 'seed-for-conv-a-32bytes-xxxxxxxxxx',
          'conv-b': 'seed-for-conv-b-32bytes-xxxxxxxxxx',
        };
        final protector = RemoteMessageProtectorImpl(
          keySeedProvider: (id) => seeds[id]!,
        );

        const plaintext = 'same text';
        final ctA = await protector.encryptText(
          conversationId: 'conv-a',
          messageId: 'msg-1',
          plaintext: plaintext,
          recipientDeviceId: 'dev-001',
        );
        final ctB = await protector.encryptText(
          conversationId: 'conv-b',
          messageId: 'msg-1',
          plaintext: plaintext,
          recipientDeviceId: 'dev-001',
        );

        expect(ctA, isNot(equals(ctB)));
        expect(
          () => protector.decryptText(
            conversationId: 'conv-b',
            messageId: 'msg-1',
            ciphertext: ctA,
          ),
          throwsA(anything),
          reason: 'Cross-conversation decryption must fail',
        );
      },
    );
  });

  // -------------------------------------------------------------------------
  // RP4-004 — Local history session seed is per-conversation and random
  // -------------------------------------------------------------------------

  group(
    'RP4-004 — Local history seed is per-conversation and randomly generated',
    () {
      late HelixRemoteDatabase db;

      setUp(() {
        db = HelixRemoteDatabase(File(':memory:'));
        db.initialize();
      });

      tearDown(() => db.close());

      test(
        'seed is created on first call and is a valid base64url-encoded 32-byte value',
        () {
          final seed = db.getOrCreateLocalHistorySessionSeed('conv-001');
          expect(seed, isNotEmpty);
          // base64Url-encoded 32 bytes = 44 characters (with padding) or 43 (without).
          expect(seed.length, greaterThanOrEqualTo(43));
        },
      );

      test(
        'same conversation returns the same seed on repeated calls (persisted)',
        () {
          final seed1 = db.getOrCreateLocalHistorySessionSeed('conv-001');
          final seed2 = db.getOrCreateLocalHistorySessionSeed('conv-001');
          expect(
            seed1,
            equals(seed2),
            reason: 'Seed must be stable across multiple calls',
          );
        },
      );

      test('different conversations get different seeds (isolation)', () {
        final seedA = db.getOrCreateLocalHistorySessionSeed('conv-a');
        final seedB = db.getOrCreateLocalHistorySessionSeed('conv-b');
        final seedC = db.getOrCreateLocalHistorySessionSeed('conv-c');
        expect(seedA, isNot(equals(seedB)));
        expect(seedB, isNot(equals(seedC)));
        expect(seedA, isNot(equals(seedC)));
      });

      test('seeds across fresh databases are distinct (no static global)', () {
        final db2 = HelixRemoteDatabase(File(':memory:'));
        db2.initialize();
        addTearDown(db2.close);

        final seed1 = db.getOrCreateLocalHistorySessionSeed('conv-001');
        final seed2 = db2.getOrCreateLocalHistorySessionSeed('conv-001');
        // Two separate databases (fresh installs) must not produce identical seeds.
        expect(
          seed1,
          isNot(equals(seed2)),
          reason: 'Seeds are per-install random, not a hard-coded static value',
        );
      });

      test('seed is stored in crypto_sessions table as local_history role', () {
        db.getOrCreateLocalHistorySessionSeed('conv-seed-check');
        final session = db.getCryptoSession('local_history:conv-seed-check');
        expect(session, isNotNull);
        expect(session!['role'], equals('local_history'));
        expect(session['root_key'], isNotEmpty);
      });
    },
  );
}
