name: helix_remote_workspace
publish_to: none

environment:
  sdk: ^3.12.0

workspace:
  - app
  - admin
  - backend
  - tool
  - packages/helix_remote_domain
  - packages/helix_remote_api
  - packages/helix_remote_crypto
  - packages/helix_remote_storage
  - packages/helix_remote_sync
  - packages/helix_remote_calls
  - packages/helix_remote_groups
  - packages/helix_remote_cli

hooks:
  user_defines:
    sqlite3:
      source: sqlcipher
