name: Verify

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  verify:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - name: Verify on Windows
        if: runner.os == 'Windows'
        shell: pwsh
        run: ./scripts/verify.ps1
      - name: Verify on Unix
        if: runner.os != 'Windows'
        shell: bash
        run: ./scripts/verify.sh
